### ISSUE TITLE
Update ES's delay parameter 

### ISSUE THREAD

**Issue by heidmic** [heidmic/suprb#103]
At the moment, the "delay" or "&" option is coded as a special version of (1, lambda)-ES. However, this is just replacing the termination criterion from a mandatory cut after n_iter generations to a potentially earlier cut once the candidate rule has not changed for delta many generations. 
In this issue this early stopping mechanism should be made independent from the replacement and allow both + and , ES to be used as the replacement operator. 
Additionally, the code can be simplified (see the bioma paper draft) to speed up the runtime.

**Comment by RomanSraj** [comment]
Early stopping is implemented elsewhere
