### ISSUE TITLE
Fix issue with population being empty after first iteration

### ISSUE THREAD

**Issue by hubanton** [heidmic/suprb#98]
Depending on the used dataset, the population may end up beeing empty after the first iteration, to avoid this dummy rule will be added into the pool

**Comment by hubanton** [comment]
Approach of adding a dummy rule and continuing the run was discared. If the model fails to provide any rules after the first main iteration, the run gets aborted with the global elitist receiving a arbitarerly bad fitness to discourage Tuners from using parameters that caused this undesirable behaviour.

**Comment by heidmic** [comment]
While this behaviour might be working for tuning situations, it is not well thought out for other cases. Especially, if using the system as stand-alone. This gets reinforced as the error is not well documented and easy to understand. On a minor note: As the PR is not yet merged, this issue should stay open until it is

**Comment by heidmic** [comment]
https://github.com/heidmic/suprb/pull/124 might have resolved this issue. After https://github.com/heidmic/suprb/pull/124, a solution is still created despite an empty pool and assigned its appropriate fitness value

**Comment by hubanton** [comment]
> #124 might have resolved this issue. After #124, a solution is still created despite an empty pool and assigned its appropriate fitness value

Agreed. As the primary problem was the Nan behaviour caused by the empty pool of rules im closing this issue.
